use crate::types::*;
use crate::vm::JNIEnv;
use crate::jni_interface::JNINativeInterface;
use crate::cast::*;
use crate::impl_basic::*;
use crate::impl_err::*;
use crate::impl_frame::*;
use crate::impl_refs::*;
use crate::impl_method::*;
use crate::impl_object::*;
use crate::impl_fields::*;
use crate::impl_strings::*;
use crate::impl_arrays::*;
use crate::impl_registry::*;
use crate::impl_new::*;
use crate::impl_misc::*;
use crate::call_method::*;
use crate::call_static::*;
use crate::call_nonvirtual::*;

pub fn build_native_interface() -> JNINativeInterface {
    JNINativeInterface {
        reserved0: None, reserved1: None, reserved2: None, reserved3: None,
        GetVersion: Some(jni_GetVersion),
        DefineClass: Some(jni_DefineClass), FindClass: Some(jni_FindClass),
        FromReflectedMethod: Some(jni_FromReflectedMethod), FromReflectedField: Some(jni_FromReflectedField),
        ToReflectedMethod: Some(jni_ToReflectedMethod), GetSuperclass: Some(jni_GetSuperclass),
        IsAssignableFrom: Some(jni_IsAssignableFrom), ToReflectedField: Some(jni_ToReflectedField),
        Throw: Some(jni_Throw), ThrowNew: Some(jni_ThrowNew),
        ExceptionOccurred: Some(jni_ExceptionOccurred), ExceptionDescribe: Some(jni_ExceptionDescribe),
        ExceptionClear: Some(jni_ExceptionClear), FatalError: Some(jni_FatalError),
        PushLocalFrame: Some(jni_PushLocalFrame), PopLocalFrame: Some(jni_PopLocalFrame),
        NewGlobalRef: Some(jni_NewGlobalRef), DeleteGlobalRef: Some(jni_DeleteGlobalRef),
        DeleteLocalRef: Some(jni_DeleteLocalRef), IsSameObject: Some(jni_IsSameObject),
        NewLocalRef: Some(jni_NewLocalRef), EnsureLocalCapacity: Some(jni_EnsureLocalCapacity),
        AllocObject: Some(jni_AllocObject),
        NewObject: Some(tno(jni_NewObject)), NewObjectV: Some(jni_NewObjectV), NewObjectA: Some(jni_NewObjectA),
        GetObjectClass: Some(jni_GetObjectClass), IsInstanceOf: Some(jni_IsInstanceOf),
        GetMethodID: Some(jni_GetMethodID),
        CallObjectMethod: Some(tc(jni_CallObjectMethod)), CallObjectMethodV: Some(jni_CallObjectMethodV), CallObjectMethodA: Some(jni_CallObjectMethodA),
        CallBooleanMethod: Some(tc(jni_CallBooleanMethod)), CallBooleanMethodV: Some(jni_CallBooleanMethodV), CallBooleanMethodA: Some(jni_CallBooleanMethodA),
        CallByteMethod: Some(tc(jni_CallByteMethod)), CallByteMethodV: Some(jni_CallByteMethodV), CallByteMethodA: Some(jni_CallByteMethodA),
        CallCharMethod: Some(tc(jni_CallCharMethod)), CallCharMethodV: Some(jni_CallCharMethodV), CallCharMethodA: Some(jni_CallCharMethodA),
        CallShortMethod: Some(tc(jni_CallShortMethod)), CallShortMethodV: Some(jni_CallShortMethodV), CallShortMethodA: Some(jni_CallShortMethodA),
        CallIntMethod: Some(tc(jni_CallIntMethod)), CallIntMethodV: Some(jni_CallIntMethodV), CallIntMethodA: Some(jni_CallIntMethodA),
        CallLongMethod: Some(tc(jni_CallLongMethod)), CallLongMethodV: Some(jni_CallLongMethodV), CallLongMethodA: Some(jni_CallLongMethodA),
        CallFloatMethod: Some(tc(jni_CallFloatMethod)), CallFloatMethodV: Some(jni_CallFloatMethodV), CallFloatMethodA: Some(jni_CallFloatMethodA),
        CallDoubleMethod: Some(tc(jni_CallDoubleMethod)), CallDoubleMethodV: Some(jni_CallDoubleMethodV), CallDoubleMethodA: Some(jni_CallDoubleMethodA),
        CallVoidMethod: Some(tc(jni_CallVoidMethod)), CallVoidMethodV: Some(jni_CallVoidMethodV), CallVoidMethodA: Some(jni_CallVoidMethodA),
        CallNonvirtualObjectMethod: Some(tcn(jni_CallNonvirtualObjectMethod)), CallNonvirtualObjectMethodV: Some(jni_CallNonvirtualObjectMethodV), CallNonvirtualObjectMethodA: Some(jni_CallNonvirtualObjectMethodA),
        CallNonvirtualBooleanMethod: Some(tcn(jni_CallNonvirtualBooleanMethod)), CallNonvirtualBooleanMethodV: Some(jni_CallNonvirtualBooleanMethodV), CallNonvirtualBooleanMethodA: Some(jni_CallNonvirtualBooleanMethodA),
        CallNonvirtualByteMethod: Some(tcn(jni_CallNonvirtualByteMethod)), CallNonvirtualByteMethodV: Some(jni_CallNonvirtualByteMethodV), CallNonvirtualByteMethodA: Some(jni_CallNonvirtualByteMethodA),
        CallNonvirtualCharMethod: Some(tcn(jni_CallNonvirtualCharMethod)), CallNonvirtualCharMethodV: Some(jni_CallNonvirtualCharMethodV), CallNonvirtualCharMethodA: Some(jni_CallNonvirtualCharMethodA),
        CallNonvirtualShortMethod: Some(tcn(jni_CallNonvirtualShortMethod)), CallNonvirtualShortMethodV: Some(jni_CallNonvirtualShortMethodV), CallNonvirtualShortMethodA: Some(jni_CallNonvirtualShortMethodA),
        CallNonvirtualIntMethod: Some(tcn(jni_CallNonvirtualIntMethod)), CallNonvirtualIntMethodV: Some(jni_CallNonvirtualIntMethodV), CallNonvirtualIntMethodA: Some(jni_CallNonvirtualIntMethodA),
        CallNonvirtualLongMethod: Some(tcn(jni_CallNonvirtualLongMethod)), CallNonvirtualLongMethodV: Some(jni_CallNonvirtualLongMethodV), CallNonvirtualLongMethodA: Some(jni_CallNonvirtualLongMethodA),
        CallNonvirtualFloatMethod: Some(tcn(jni_CallNonvirtualFloatMethod)), CallNonvirtualFloatMethodV: Some(jni_CallNonvirtualFloatMethodV), CallNonvirtualFloatMethodA: Some(jni_CallNonvirtualFloatMethodA),
        CallNonvirtualDoubleMethod: Some(tcn(jni_CallNonvirtualDoubleMethod)), CallNonvirtualDoubleMethodV: Some(jni_CallNonvirtualDoubleMethodV), CallNonvirtualDoubleMethodA: Some(jni_CallNonvirtualDoubleMethodA),
        CallNonvirtualVoidMethod: Some(tcn(jni_CallNonvirtualVoidMethod)), CallNonvirtualVoidMethodV: Some(jni_CallNonvirtualVoidMethodV), CallNonvirtualVoidMethodA: Some(jni_CallNonvirtualVoidMethodA),
        GetFieldID: Some(jni_GetFieldID),
        GetObjectField: Some(jni_GetObjectField), GetBooleanField: Some(jni_GetBooleanField),
        GetByteField: Some(jni_GetByteField), GetCharField: Some(jni_GetCharField),
        GetShortField: Some(jni_GetShortField), GetIntField: Some(jni_GetIntField),
        GetLongField: Some(jni_GetLongField), GetFloatField: Some(jni_GetFloatField),
        GetDoubleField: Some(jni_GetDoubleField),
        SetObjectField: Some(jni_SetObjectField), SetBooleanField: Some(jni_SetBooleanField),
        SetByteField: Some(jni_SetByteField), SetCharField: Some(jni_SetCharField),
        SetShortField: Some(jni_SetShortField), SetIntField: Some(jni_SetIntField),
        SetLongField: Some(jni_SetLongField), SetFloatField: Some(jni_SetFloatField),
        SetDoubleField: Some(jni_SetDoubleField),
        GetStaticMethodID: Some(jni_GetStaticMethodID),
        CallStaticObjectMethod: Some(tcs(jni_CallStaticObjectMethod)), CallStaticObjectMethodV: Some(jni_CallStaticObjectMethodV), CallStaticObjectMethodA: Some(jni_CallStaticObjectMethodA),
        CallStaticBooleanMethod: Some(tcs(jni_CallStaticBooleanMethod)), CallStaticBooleanMethodV: Some(jni_CallStaticBooleanMethodV), CallStaticBooleanMethodA: Some(jni_CallStaticBooleanMethodA),
        CallStaticByteMethod: Some(tcs(jni_CallStaticByteMethod)), CallStaticByteMethodV: Some(jni_CallStaticByteMethodV), CallStaticByteMethodA: Some(jni_CallStaticByteMethodA),
        CallStaticCharMethod: Some(tcs(jni_CallStaticCharMethod)), CallStaticCharMethodV: Some(jni_CallStaticCharMethodV), CallStaticCharMethodA: Some(jni_CallStaticCharMethodA),
        CallStaticShortMethod: Some(tcs(jni_CallStaticShortMethod)), CallStaticShortMethodV: Some(jni_CallStaticShortMethodV), CallStaticShortMethodA: Some(jni_CallStaticShortMethodA),
        CallStaticIntMethod: Some(tcs(jni_CallStaticIntMethod)), CallStaticIntMethodV: Some(jni_CallStaticIntMethodV), CallStaticIntMethodA: Some(jni_CallStaticIntMethodA),
        CallStaticLongMethod: Some(tcs(jni_CallStaticLongMethod)), CallStaticLongMethodV: Some(jni_CallStaticLongMethodV), CallStaticLongMethodA: Some(jni_CallStaticLongMethodA),
        CallStaticFloatMethod: Some(tcs(jni_CallStaticFloatMethod)), CallStaticFloatMethodV: Some(jni_CallStaticFloatMethodV), CallStaticFloatMethodA: Some(jni_CallStaticFloatMethodA),
        CallStaticDoubleMethod: Some(tcs(jni_CallStaticDoubleMethod)), CallStaticDoubleMethodV: Some(jni_CallStaticDoubleMethodV), CallStaticDoubleMethodA: Some(jni_CallStaticDoubleMethodA),
        CallStaticVoidMethod: Some(tcs(jni_CallStaticVoidMethod)), CallStaticVoidMethodV: Some(jni_CallStaticVoidMethodV), CallStaticVoidMethodA: Some(jni_CallStaticVoidMethodA),
        GetStaticFieldID: Some(jni_GetStaticFieldID),
        GetStaticObjectField: Some(jni_GetStaticObjectField), GetStaticBooleanField: Some(jni_GetStaticBooleanField),
        GetStaticByteField: Some(jni_GetStaticByteField), GetStaticCharField: Some(jni_GetStaticCharField),
        GetStaticShortField: Some(jni_GetStaticShortField), GetStaticIntField: Some(jni_GetStaticIntField),
        GetStaticLongField: Some(jni_GetStaticLongField), GetStaticFloatField: Some(jni_GetStaticFloatField),
        GetStaticDoubleField: Some(jni_GetStaticDoubleField),
        SetStaticObjectField: Some(jni_SetStaticObjectField), SetStaticBooleanField: Some(jni_SetStaticBooleanField),
        SetStaticByteField: Some(jni_SetStaticByteField), SetStaticCharField: Some(jni_SetStaticCharField),
        SetStaticShortField: Some(jni_SetStaticShortField), SetStaticIntField: Some(jni_SetStaticIntField),
        SetStaticLongField: Some(jni_SetStaticLongField), SetStaticFloatField: Some(jni_SetStaticFloatField),
        SetStaticDoubleField: Some(jni_SetStaticDoubleField),
        NewString: Some(jni_NewString), GetStringLength: Some(jni_GetStringLength),
        GetStringChars: Some(jni_GetStringChars), ReleaseStringChars: Some(jni_ReleaseStringChars),
        NewStringUTF: Some(jni_NewStringUTF), GetStringUTFLength: Some(jni_GetStringUTFLength),
        GetStringUTFChars: Some(jni_GetStringUTFChars), ReleaseStringUTFChars: Some(jni_ReleaseStringUTFChars),
        GetArrayLength: Some(jni_GetArrayLength), NewObjectArray: Some(jni_NewObjectArray),
        GetObjectArrayElement: Some(jni_GetObjectArrayElement), SetObjectArrayElement: Some(jni_SetObjectArrayElement),
        NewBooleanArray: Some(jni_NewBooleanArray), NewByteArray: Some(jni_NewByteArray),
        NewCharArray: Some(jni_NewCharArray), NewShortArray: Some(jni_NewShortArray),
        NewIntArray: Some(jni_NewIntArray), NewLongArray: Some(jni_NewLongArray),
        NewFloatArray: Some(jni_NewFloatArray), NewDoubleArray: Some(jni_NewDoubleArray),
        GetBooleanArrayElements: Some(jni_GetBooleanArrayElements), GetByteArrayElements: Some(jni_GetByteArrayElements),
        GetCharArrayElements: Some(jni_GetCharArrayElements), GetShortArrayElements: Some(jni_GetShortArrayElements),
        GetIntArrayElements: Some(jni_GetIntArrayElements), GetLongArrayElements: Some(jni_GetLongArrayElements),
        GetFloatArrayElements: Some(jni_GetFloatArrayElements), GetDoubleArrayElements: Some(jni_GetDoubleArrayElements),
        ReleaseBooleanArrayElements: Some(jni_ReleaseBooleanArrayElements), ReleaseByteArrayElements: Some(jni_ReleaseByteArrayElements),
        ReleaseCharArrayElements: Some(jni_ReleaseCharArrayElements), ReleaseShortArrayElements: Some(jni_ReleaseShortArrayElements),
        ReleaseIntArrayElements: Some(jni_ReleaseIntArrayElements), ReleaseLongArrayElements: Some(jni_ReleaseLongArrayElements),
        ReleaseFloatArrayElements: Some(jni_ReleaseFloatArrayElements), ReleaseDoubleArrayElements: Some(jni_ReleaseDoubleArrayElements),
        GetBooleanArrayRegion: Some(jni_GetBooleanArrayRegion), GetByteArrayRegion: Some(jni_GetByteArrayRegion),
        GetCharArrayRegion: Some(jni_GetCharArrayRegion), GetShortArrayRegion: Some(jni_GetShortArrayRegion),
        GetIntArrayRegion: Some(jni_GetIntArrayRegion), GetLongArrayRegion: Some(jni_GetLongArrayRegion),
        GetFloatArrayRegion: Some(jni_GetFloatArrayRegion), GetDoubleArrayRegion: Some(jni_GetDoubleArrayRegion),
        SetBooleanArrayRegion: Some(jni_SetBooleanArrayRegion), SetByteArrayRegion: Some(jni_SetByteArrayRegion),
        SetCharArrayRegion: Some(jni_SetCharArrayRegion), SetShortArrayRegion: Some(jni_SetShortArrayRegion),
        SetIntArrayRegion: Some(jni_SetIntArrayRegion), SetLongArrayRegion: Some(jni_SetLongArrayRegion),
        SetFloatArrayRegion: Some(jni_SetFloatArrayRegion), SetDoubleArrayRegion: Some(jni_SetDoubleArrayRegion),
        RegisterNatives: Some(jni_RegisterNatives), UnregisterNatives: Some(jni_UnregisterNatives),
        MonitorEnter: Some(jni_MonitorEnter), MonitorExit: Some(jni_MonitorExit),
        GetJavaVM: Some(jni_GetJavaVM),
        GetStringRegion: Some(jni_GetStringRegion), GetStringUTFRegion: Some(jni_GetStringUTFRegion),
        GetPrimitiveArrayCritical: Some(jni_GetPrimitiveArrayCritical), ReleasePrimitiveArrayCritical: Some(jni_ReleasePrimitiveArrayCritical),
        GetStringCritical: Some(jni_GetStringCritical), ReleaseStringCritical: Some(jni_ReleaseStringCritical),
        NewWeakGlobalRef: Some(jni_NewWeakGlobalRef), DeleteWeakGlobalRef: Some(jni_DeleteWeakGlobalRef),
        ExceptionCheck: Some(jni_ExceptionCheck),
        NewDirectByteBuffer: Some(jni_NewDirectByteBuffer), GetDirectBufferAddress: Some(jni_GetDirectBufferAddress),
        GetDirectBufferCapacity: Some(jni_GetDirectBufferCapacity), GetObjectRefType: Some(jni_GetObjectRefType),
    }
}
