use crate::types::*;
use crate::vm::JNIEnv;
use std::ffi::{c_char, c_void};

#[repr(C)]
pub struct JNINativeInterface {
    pub reserved0: Option<unsafe extern "C" fn()>,
    pub reserved1: Option<unsafe extern "C" fn()>,
    pub reserved2: Option<unsafe extern "C" fn()>,
    pub reserved3: Option<unsafe extern "C" fn()>,
    pub GetVersion: Option<unsafe extern "C" fn(env: *mut JNIEnv) -> jint>,
    pub DefineClass: Option<unsafe extern "C" fn(env: *mut JNIEnv, name: *const c_char, loader: jobject, buf: *const jbyte, len: jsize) -> jclass>,
    pub FindClass: Option<unsafe extern "C" fn(env: *mut JNIEnv, name: *const c_char) -> jclass>,
    pub FromReflectedMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, method: jobject) -> jmethodID>,
    pub FromReflectedField: Option<unsafe extern "C" fn(env: *mut JNIEnv, field: jobject) -> jfieldID>,
    pub ToReflectedMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, cls: jclass, methodID: jmethodID, isStatic: jboolean) -> jobject>,
    pub GetSuperclass: Option<unsafe extern "C" fn(env: *mut JNIEnv, sub: jclass) -> jclass>,
    pub IsAssignableFrom: Option<unsafe extern "C" fn(env: *mut JNIEnv, sub: jclass, sup: jclass) -> jboolean>,
    pub ToReflectedField: Option<unsafe extern "C" fn(env: *mut JNIEnv, cls: jclass, fieldID: jfieldID, isStatic: jboolean) -> jobject>,
    pub Throw: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jthrowable) -> jint>,
    pub ThrowNew: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, msg: *const c_char) -> jint>,
    pub ExceptionOccurred: Option<unsafe extern "C" fn(env: *mut JNIEnv) -> jthrowable>,
    pub ExceptionDescribe: Option<unsafe extern "C" fn(env: *mut JNIEnv)>,
    pub ExceptionClear: Option<unsafe extern "C" fn(env: *mut JNIEnv)>,
    pub FatalError: Option<unsafe extern "C" fn(env: *mut JNIEnv, msg: *const c_char)>,
    pub PushLocalFrame: Option<unsafe extern "C" fn(env: *mut JNIEnv, capacity: jint) -> jint>,
    pub PopLocalFrame: Option<unsafe extern "C" fn(env: *mut JNIEnv, result: jobject) -> jobject>,
    pub NewGlobalRef: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject) -> jobject>,
    pub DeleteGlobalRef: Option<unsafe extern "C" fn(env: *mut JNIEnv, globalRef: jobject)>,
    pub DeleteLocalRef: Option<unsafe extern "C" fn(env: *mut JNIEnv, localRef: jobject)>,
    pub IsSameObject: Option<unsafe extern "C" fn(env: *mut JNIEnv, ref1: jobject, ref2: jobject) -> jboolean>,
    pub NewLocalRef: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject) -> jobject>,
    pub EnsureLocalCapacity: Option<unsafe extern "C" fn(env: *mut JNIEnv, capacity: jint) -> jint>,
    pub AllocObject: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass) -> jobject>,
    pub NewObject: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID) -> jobject>,
    pub NewObjectV: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jobject>,
    pub NewObjectA: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jobject>,
    pub GetObjectClass: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject) -> jclass>,
    pub IsInstanceOf: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass) -> jboolean>,
    pub GetMethodID: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, name: *const c_char, sig: *const c_char) -> jmethodID>,
    pub CallObjectMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID) -> jobject>,
    pub CallObjectMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jobject>,
    pub CallObjectMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jobject>,
    pub CallBooleanMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID) -> jboolean>,
    pub CallBooleanMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jboolean>,
    pub CallBooleanMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jboolean>,
    pub CallByteMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID) -> jbyte>,
    pub CallByteMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jbyte>,
    pub CallByteMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jbyte>,
    pub CallCharMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID) -> jchar>,
    pub CallCharMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jchar>,
    pub CallCharMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jchar>,
    pub CallShortMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID) -> jshort>,
    pub CallShortMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jshort>,
    pub CallShortMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jshort>,
    pub CallIntMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID) -> jint>,
    pub CallIntMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jint>,
    pub CallIntMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jint>,
    pub CallLongMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID) -> jlong>,
    pub CallLongMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jlong>,
    pub CallLongMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jlong>,
    pub CallFloatMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID) -> jfloat>,
    pub CallFloatMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jfloat>,
    pub CallFloatMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jfloat>,
    pub CallDoubleMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID) -> jdouble>,
    pub CallDoubleMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jdouble>,
    pub CallDoubleMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue) -> jdouble>,
    pub CallVoidMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID)>,
    pub CallVoidMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue)>,
    pub CallVoidMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, methodID: jmethodID, args: *mut jvalue)>,
    pub CallNonvirtualObjectMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID) -> jobject>,
    pub CallNonvirtualObjectMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jobject>,
    pub CallNonvirtualObjectMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jobject>,
    pub CallNonvirtualBooleanMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID) -> jboolean>,
    pub CallNonvirtualBooleanMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jboolean>,
    pub CallNonvirtualBooleanMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jboolean>,
    pub CallNonvirtualByteMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID) -> jbyte>,
    pub CallNonvirtualByteMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jbyte>,
    pub CallNonvirtualByteMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jbyte>,
    pub CallNonvirtualCharMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID) -> jchar>,
    pub CallNonvirtualCharMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jchar>,
    pub CallNonvirtualCharMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jchar>,
    pub CallNonvirtualShortMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID) -> jshort>,
    pub CallNonvirtualShortMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jshort>,
    pub CallNonvirtualShortMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jshort>,
    pub CallNonvirtualIntMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID) -> jint>,
    pub CallNonvirtualIntMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jint>,
    pub CallNonvirtualIntMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jint>,
    pub CallNonvirtualLongMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID) -> jlong>,
    pub CallNonvirtualLongMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jlong>,
    pub CallNonvirtualLongMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jlong>,
    pub CallNonvirtualFloatMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID) -> jfloat>,
    pub CallNonvirtualFloatMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jfloat>,
    pub CallNonvirtualFloatMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jfloat>,
    pub CallNonvirtualDoubleMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID) -> jdouble>,
    pub CallNonvirtualDoubleMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jdouble>,
    pub CallNonvirtualDoubleMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jdouble>,
    pub CallNonvirtualVoidMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID)>,
    pub CallNonvirtualVoidMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue)>,
    pub CallNonvirtualVoidMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, clazz: jclass, methodID: jmethodID, args: *mut jvalue)>,
    pub GetFieldID: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, name: *const c_char, sig: *const c_char) -> jfieldID>,
    pub GetObjectField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID) -> jobject>,
    pub GetBooleanField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID) -> jboolean>,
    pub GetByteField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID) -> jbyte>,
    pub GetCharField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID) -> jchar>,
    pub GetShortField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID) -> jshort>,
    pub GetIntField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID) -> jint>,
    pub GetLongField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID) -> jlong>,
    pub GetFloatField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID) -> jfloat>,
    pub GetDoubleField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID) -> jdouble>,
    pub SetObjectField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID, value: jobject)>,
    pub SetBooleanField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID, value: jboolean)>,
    pub SetByteField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID, value: jbyte)>,
    pub SetCharField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID, value: jchar)>,
    pub SetShortField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID, value: jshort)>,
    pub SetIntField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID, value: jint)>,
    pub SetLongField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID, value: jlong)>,
    pub SetFloatField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID, value: jfloat)>,
    pub SetDoubleField: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject, fieldID: jfieldID, value: jdouble)>,
    pub GetStaticMethodID: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, name: *const c_char, sig: *const c_char) -> jmethodID>,
    pub CallStaticObjectMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID) -> jobject>,
    pub CallStaticObjectMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jobject>,
    pub CallStaticObjectMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jobject>,
    pub CallStaticBooleanMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID) -> jboolean>,
    pub CallStaticBooleanMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jboolean>,
    pub CallStaticBooleanMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jboolean>,
    pub CallStaticByteMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID) -> jbyte>,
    pub CallStaticByteMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jbyte>,
    pub CallStaticByteMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jbyte>,
    pub CallStaticCharMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID) -> jchar>,
    pub CallStaticCharMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jchar>,
    pub CallStaticCharMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jchar>,
    pub CallStaticShortMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID) -> jshort>,
    pub CallStaticShortMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jshort>,
    pub CallStaticShortMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jshort>,
    pub CallStaticIntMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID) -> jint>,
    pub CallStaticIntMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jint>,
    pub CallStaticIntMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jint>,
    pub CallStaticLongMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID) -> jlong>,
    pub CallStaticLongMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jlong>,
    pub CallStaticLongMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jlong>,
    pub CallStaticFloatMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID) -> jfloat>,
    pub CallStaticFloatMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jfloat>,
    pub CallStaticFloatMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jfloat>,
    pub CallStaticDoubleMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID) -> jdouble>,
    pub CallStaticDoubleMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jdouble>,
    pub CallStaticDoubleMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue) -> jdouble>,
    pub CallStaticVoidMethod: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID)>,
    pub CallStaticVoidMethodV: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue)>,
    pub CallStaticVoidMethodA: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methodID: jmethodID, args: *mut jvalue)>,
    pub GetStaticFieldID: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, name: *const c_char, sig: *const c_char) -> jfieldID>,
    pub GetStaticObjectField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID) -> jobject>,
    pub GetStaticBooleanField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID) -> jboolean>,
    pub GetStaticByteField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID) -> jbyte>,
    pub GetStaticCharField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID) -> jchar>,
    pub GetStaticShortField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID) -> jshort>,
    pub GetStaticIntField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID) -> jint>,
    pub GetStaticLongField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID) -> jlong>,
    pub GetStaticFloatField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID) -> jfloat>,
    pub GetStaticDoubleField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID) -> jdouble>,
    pub SetStaticObjectField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID, value: jobject)>,
    pub SetStaticBooleanField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID, value: jboolean)>,
    pub SetStaticByteField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID, value: jbyte)>,
    pub SetStaticCharField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID, value: jchar)>,
    pub SetStaticShortField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID, value: jshort)>,
    pub SetStaticIntField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID, value: jint)>,
    pub SetStaticLongField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID, value: jlong)>,
    pub SetStaticFloatField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID, value: jfloat)>,
    pub SetStaticDoubleField: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, fieldID: jfieldID, value: jdouble)>,
    pub NewString: Option<unsafe extern "C" fn(env: *mut JNIEnv, unicode: *const jchar, len: jsize) -> jstring>,
    pub GetStringLength: Option<unsafe extern "C" fn(env: *mut JNIEnv, str: jstring) -> jsize>,
    pub GetStringChars: Option<unsafe extern "C" fn(env: *mut JNIEnv, str: jstring, isCopy: *mut jboolean) -> *const jchar>,
    pub ReleaseStringChars: Option<unsafe extern "C" fn(env: *mut JNIEnv, str: jstring, chars: *const jchar)>,
    pub NewStringUTF: Option<unsafe extern "C" fn(env: *mut JNIEnv, utf: *const c_char) -> jstring>,
    pub GetStringUTFLength: Option<unsafe extern "C" fn(env: *mut JNIEnv, str: jstring) -> jsize>,
    pub GetStringUTFChars: Option<unsafe extern "C" fn(env: *mut JNIEnv, str: jstring, isCopy: *mut jboolean) -> *const c_char>,
    pub ReleaseStringUTFChars: Option<unsafe extern "C" fn(env: *mut JNIEnv, str: jstring, utf: *const c_char)>,
    pub GetArrayLength: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jarray) -> jsize>,
    pub NewObjectArray: Option<unsafe extern "C" fn(env: *mut JNIEnv, len: jsize, clazz: jclass, init: jobject) -> jobjectArray>,
    pub GetObjectArrayElement: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jobjectArray, index: jsize) -> jobject>,
    pub SetObjectArrayElement: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jobjectArray, index: jsize, val: jobject)>,
    pub NewBooleanArray: Option<unsafe extern "C" fn(env: *mut JNIEnv, len: jsize) -> jbooleanArray>,
    pub NewByteArray: Option<unsafe extern "C" fn(env: *mut JNIEnv, len: jsize) -> jbyteArray>,
    pub NewCharArray: Option<unsafe extern "C" fn(env: *mut JNIEnv, len: jsize) -> jcharArray>,
    pub NewShortArray: Option<unsafe extern "C" fn(env: *mut JNIEnv, len: jsize) -> jshortArray>,
    pub NewIntArray: Option<unsafe extern "C" fn(env: *mut JNIEnv, len: jsize) -> jintArray>,
    pub NewLongArray: Option<unsafe extern "C" fn(env: *mut JNIEnv, len: jsize) -> jlongArray>,
    pub NewFloatArray: Option<unsafe extern "C" fn(env: *mut JNIEnv, len: jsize) -> jfloatArray>,
    pub NewDoubleArray: Option<unsafe extern "C" fn(env: *mut JNIEnv, len: jsize) -> jdoubleArray>,
    pub GetBooleanArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jbooleanArray, isCopy: *mut jboolean) -> *mut jboolean>,
    pub GetByteArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jbyteArray, isCopy: *mut jboolean) -> *mut jbyte>,
    pub GetCharArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jcharArray, isCopy: *mut jboolean) -> *mut jchar>,
    pub GetShortArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jshortArray, isCopy: *mut jboolean) -> *mut jshort>,
    pub GetIntArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jintArray, isCopy: *mut jboolean) -> *mut jint>,
    pub GetLongArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jlongArray, isCopy: *mut jboolean) -> *mut jlong>,
    pub GetFloatArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jfloatArray, isCopy: *mut jboolean) -> *mut jfloat>,
    pub GetDoubleArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jdoubleArray, isCopy: *mut jboolean) -> *mut jdouble>,
    pub ReleaseBooleanArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jbooleanArray, elems: *mut jboolean, mode: jint)>,
    pub ReleaseByteArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jbyteArray, elems: *mut jbyte, mode: jint)>,
    pub ReleaseCharArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jcharArray, elems: *mut jchar, mode: jint)>,
    pub ReleaseShortArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jshortArray, elems: *mut jshort, mode: jint)>,
    pub ReleaseIntArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jintArray, elems: *mut jint, mode: jint)>,
    pub ReleaseLongArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jlongArray, elems: *mut jlong, mode: jint)>,
    pub ReleaseFloatArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jfloatArray, elems: *mut jfloat, mode: jint)>,
    pub ReleaseDoubleArrayElements: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jdoubleArray, elems: *mut jdouble, mode: jint)>,
    pub GetBooleanArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jbooleanArray, start: jsize, len: jsize, buf: *mut jboolean)>,
    pub GetByteArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jbyteArray, start: jsize, len: jsize, buf: *mut jbyte)>,
    pub GetCharArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jcharArray, start: jsize, len: jsize, buf: *mut jchar)>,
    pub GetShortArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jshortArray, start: jsize, len: jsize, buf: *mut jshort)>,
    pub GetIntArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jintArray, start: jsize, len: jsize, buf: *mut jint)>,
    pub GetLongArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jlongArray, start: jsize, len: jsize, buf: *mut jlong)>,
    pub GetFloatArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jfloatArray, start: jsize, len: jsize, buf: *mut jfloat)>,
    pub GetDoubleArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jdoubleArray, start: jsize, len: jsize, buf: *mut jdouble)>,
    pub SetBooleanArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jbooleanArray, start: jsize, len: jsize, buf: *const jboolean)>,
    pub SetByteArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jbyteArray, start: jsize, len: jsize, buf: *const jbyte)>,
    pub SetCharArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jcharArray, start: jsize, len: jsize, buf: *const jchar)>,
    pub SetShortArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jshortArray, start: jsize, len: jsize, buf: *const jshort)>,
    pub SetIntArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jintArray, start: jsize, len: jsize, buf: *const jint)>,
    pub SetLongArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jlongArray, start: jsize, len: jsize, buf: *const jlong)>,
    pub SetFloatArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jfloatArray, start: jsize, len: jsize, buf: *const jfloat)>,
    pub SetDoubleArrayRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jdoubleArray, start: jsize, len: jsize, buf: *const jdouble)>,
    pub RegisterNatives: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass, methods: *const JNINativeMethod, nMethods: jint) -> jint>,
    pub UnregisterNatives: Option<unsafe extern "C" fn(env: *mut JNIEnv, clazz: jclass) -> jint>,
    pub MonitorEnter: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject) -> jint>,
    pub MonitorExit: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject) -> jint>,
    pub GetJavaVM: Option<unsafe extern "C" fn(env: *mut JNIEnv, vm: *mut crate::vm::JavaVM) -> jint>,
    pub GetStringRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, str: jstring, start: jsize, len: jsize, buf: *mut jchar)>,
    pub GetStringUTFRegion: Option<unsafe extern "C" fn(env: *mut JNIEnv, str: jstring, start: jsize, len: jsize, buf: *mut c_char)>,
    pub GetPrimitiveArrayCritical: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jarray, isCopy: *mut jboolean) -> *mut c_void>,
    pub ReleasePrimitiveArrayCritical: Option<unsafe extern "C" fn(env: *mut JNIEnv, array: jarray, carray: *mut c_void, mode: jint)>,
    pub GetStringCritical: Option<unsafe extern "C" fn(env: *mut JNIEnv, str: jstring, isCopy: *mut jboolean) -> *const jchar>,
    pub ReleaseStringCritical: Option<unsafe extern "C" fn(env: *mut JNIEnv, str: jstring, cstring: *const jchar)>,
    pub NewWeakGlobalRef: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject) -> jweak>,
    pub DeleteWeakGlobalRef: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jweak)>,
    pub ExceptionCheck: Option<unsafe extern "C" fn(env: *mut JNIEnv) -> jboolean>,
    pub NewDirectByteBuffer: Option<unsafe extern "C" fn(env: *mut JNIEnv, address: *mut c_void, capacity: jlong) -> jobject>,
    pub GetDirectBufferAddress: Option<unsafe extern "C" fn(env: *mut JNIEnv, buf: jobject) -> *mut c_void>,
    pub GetDirectBufferCapacity: Option<unsafe extern "C" fn(env: *mut JNIEnv, buf: jobject) -> jlong>,
    pub GetObjectRefType: Option<unsafe extern "C" fn(env: *mut JNIEnv, obj: jobject) -> jobjectRefType>,
}
