[package]
name = "simple-ipc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["net", "io-util", "sync", "rt", "process", "fs", "time", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_cbor = "0.11"
bytes = "1"
thiserror = "1"
log = "0.4"

[dev-dependencies]
bytes = "1"

[lints]
workspace = true
