[workspace]
resolver = "2"
members = [
    "crates/minecraft-imported-symbols",
    "crates/axml-parser",
    "crates/simple-ipc",
    "crates/daemon-utils",
    "crates/msa-daemon-client",
    "crates/cll-telemetry",
    "crates/libc-shim",
    "crates/libjnivm-sys",
    "crates/util",
    "crates/common",
    "crates/apkinfo",
    "crates/linker",
    "crates/client",
    "crates/corelib",
    "crates/cpp-bridge-sys",
]

[workspace.lints.rust]
non_snake_case = "allow"
non_upper_case_globals = "allow"
non_camel_case_types = "allow"
