pub mod types;
pub mod bionic_conv;
pub mod pthreads;
pub mod errno;
pub mod assert;
pub mod stdlib;
pub mod string;
pub mod memory;
pub mod ctype;
pub mod stdio;
pub mod unistd;
pub mod mmap;
pub mod signal_;
pub mod time;
pub mod locale;
pub mod socket;
pub mod stat;
pub mod dir;
pub mod data;
pub mod file;
pub mod misc;
pub mod path_rewrite;

use std::ffi::c_int;
use std::ffi::c_void;
use std::ffi::CString;
use types::*;

// C-backed variadic wrappers (va_start/va_end in C, not Rust)
extern "C" {
    fn get_shim_sscanf() -> *mut c_void;
    fn get_shim_printf() -> *mut c_void;
    fn get_shim_sprintf() -> *mut c_void;
    fn get_shim_snprintf() -> *mut c_void;
    fn get_shim_asprintf() -> *mut c_void;
    fn get_shim___snprintf_chk() -> *mut c_void;
    fn get_shim_scanf() -> *mut c_void;
    fn get_shim_swprintf() -> *mut c_void;
    fn get_shim_syscall() -> *mut c_void;
    fn get_shim_fprintf() -> *mut c_void;
    fn get_shim_fscanf() -> *mut c_void;
}

type va_list = *mut c_void;
pub type jmp_buf = [u8; 200];
pub type sigjmp_buf = [u8; 200];

#[no_mangle]
pub unsafe extern "C" fn get_shimmed_symbols_fill(buf: *mut shimmed_symbol) {
    file::init_standard_files();
    for (j, sym) in SHIMMED_SYMBOLS.iter().enumerate() {
        let name = CString::new(*sym).unwrap();
        (*buf.add(j)).name = name.into_raw();
        (*buf.add(j)).value = get_symbol_ptr(sym);
    }
}

#[no_mangle]
pub unsafe extern "C" fn get_shimmed_symbols_len() -> usize {
    SHIMMED_SYMBOLS.len()
}

static SHIMMED_SYMBOLS: &[&str] = &[
    "__errno", "__set_errno",
    "__assert", "__assert2",
    "__stack_chk_fail",
    "__stack_chk_guard",
    "android_set_abort_message",
    "__cxa_atexit", "__cxa_finalize",
    "abort", "atexit", "exit", "_Exit", "_exit",
    "system", "getenv", "putenv", "setenv", "unsetenv",
    "realpath",
    "atoi", "atol", "atoll", "atof",
    "strtol", "strtoul", "strtoll", "strtoull",
    "strtof", "strtod", "strtold",
    "strtoq", "strtouq", "strtoimax", "strtoumax",
    "abs", "ldexp", "bsearch", "qsort",
    "malloc", "free", "calloc", "realloc", "valloc",
    "memalign", "posix_memalign", "malloc_usable_size",
    "memcpy", "__memcpy_chk",
    "memmove", "__memmove_chk",
    "memset", "__memset_chk",
    "memcmp", "memchr", "memmem",
    "bcmp", "bcopy", "bzero", "ffs",
    "index", "rindex",
    "strlen", "__strlen_chk",
    "strcmp", "strncmp",
    "strcpy", "__strcpy_chk",
    "strncpy", "__strncpy_chk",
    "strcat", "__strcat_chk",
    "strncat", "__strncat_chk",
    "strdup", "strndup",
    "strchr", "strrchr",
    "strstr", "strtok", "strtok_r",
    "strerror", "strerror_r",
    "strnlen", "strlcpy",
    "strcasecmp", "strncasecmp",
    "strcoll", "strxfrm",
    "strsep", "strcspn", "strpbrk", "strspn", "strsignal",
    "memccpy", "basename",
    "isalnum", "isalpha", "isblank", "iscntrl", "isdigit", "isgraph",
    "islower", "isprint", "ispunct", "isspace", "isupper", "isxdigit", "isascii",
    "tolower", "toupper",
    "writev",
        "printf", "sprintf", "snprintf", "scanf",
        "vsprintf", "vsnprintf", "vscanf",
        "swprintf",
        "puts", "putchar", "getchar", "perror",
        "remove", "rename",
    "open", "open64", "close", "read", "write",
    "pread", "pwrite", "lseek", "lseek64",
    "dup", "dup2", "pipe",
    "access", "unlink", "unlinkat",
    "rmdir", "mkdir", "link", "symlink", "readlink",
    "chdir", "fchdir", "getcwd",
    "chown", "fchown", "lchown",
    "getuid", "getgid", "geteuid", "getegid",
    "getpid", "getppid", "getpgrp",
    "fork", "vfork",
    "execv", "execvp", "execl", "execle", "execlp",
    "isatty", "alarm", "sleep", "usleep", "pause",
    "fsync", "fdatasync", "sync",
    "gethostname", "getpagesize",
    "truncate", "ftruncate",
    "nice", "getdtablesize",
    "mmap", "munmap", "mprotect", "madvise", "msync", "mlock", "munlock",
    "signal", "raise", "sigaction", "sigprocmask",
    "sigemptyset", "sigfillset", "sigaddset", "sigdelset",
    "time", "clock", "difftime", "mktime",
    "gmtime", "gmtime_r", "localtime", "localtime_r",
    "strftime", "strptime",
    "asctime", "ctime", "asctime_r", "ctime_r",
    "tzset",
    "tzname",
    "daylight",
    "timezone",
    "nanosleep",
    "gettimeofday", "clock_gettime", "clock_getres",
    "setlocale", "localeconv",
    "socket", "bind", "connect", "listen",
    "accept", "accept4",
    "send", "recv", "sendto", "recvfrom",
    "getsockname", "getpeername",
    "getsockopt", "setsockopt", "shutdown",
    "getaddrinfo", "freeaddrinfo", "getnameinfo",
    "if_nametoindex", "if_indextoname",
    "sendfile",
    "stat", "fstat", "lstat",
    "stat64", "fstat64", "lstat64",
    "mkfifo", "mknod",
    "utime", "utimes", "utimensat", "futimens",
    "statfs", "fstatfs", "statvfs", "fstatvfs",
    "opendir", "closedir", "readdir", "readdir_r",
    "rewinddir", "seekdir", "telldir",
    "scandir", "alphasort", "versionsort",
    "mkdtemp",
    "ioctl", "fcntl",
    "poll",
    "getrlimit", "setrlimit", "getrusage",
    "getpriority", "setpriority",
    "sched_yield", "sched_get_priority_min", "sched_get_priority_max",
    "sched_setaffinity", "sched_getaffinity",
    "openlog", "closelog", "syslog",
    "uname",
    "random", "srandom", "rand", "srand", "rand_r",
    "dlopen", "dlsym", "dlclose", "dlerror", "dladdr",
    "fnmatch",
    "wcslen", "wcscpy", "wcsncpy", "wcscmp", "wcscat",
    "isnan", "finite",
    "_Znwj", "_Znaj", "_Znwm", "_Znam",
    "_ZdlPv", "_ZdaPv",
    "_ZnwjSt11align_val_t", "_ZnwmSt11align_val_t",
    "gettid", "getrandom", "syscall",
    "arc4random_buf", "arc4random", "getentropy",
    "mblen", "mbtowc", "wctomb", "mbstowcs", "wcstombs",
    "wcsrtombs", "mbsrtowcs",
    "epoll_create", "epoll_create1", "epoll_ctl", "epoll_wait",
    "eventfd",
    "sem_init", "sem_destroy", "sem_wait", "sem_timedwait", "sem_post",
    "setjmp", "longjmp",
    "sysconf",
    "__system_property_find", "__system_property_get", "__system_property_read_callback",
    // pthreads
    "pthread_create", "pthread_join", "pthread_detach", "pthread_kill", "pthread_self", "pthread_equal", "pthread_atfork",
    "pthread_setschedparam", "pthread_getschedparam", "pthread_getattr_np",
    "pthread_attr_init", "pthread_attr_destroy",
    "pthread_attr_setdetachstate", "pthread_attr_getdetachstate",
    "pthread_attr_setschedparam", "pthread_attr_getschedparam",
    "pthread_attr_setstacksize", "pthread_attr_getstack", "pthread_attr_getstacksize",
    "pthread_setname_np",
    "pthread_mutex_init", "pthread_mutex_destroy",
    "pthread_mutex_lock", "pthread_mutex_unlock", "pthread_mutex_trylock",
    "pthread_mutexattr_init", "pthread_mutexattr_destroy",
    "pthread_mutexattr_settype", "pthread_mutexattr_gettype",
    "pthread_cond_init", "pthread_cond_destroy",
    "pthread_cond_wait", "pthread_cond_broadcast", "pthread_cond_signal", "pthread_cond_timedwait",
    "pthread_cond_timedwait_monotonic_np",
    "pthread_condattr_init", "pthread_condattr_destroy",
    "pthread_condattr_setclock", "pthread_condattr_getclock",
    "pthread_rwlock_init", "pthread_rwlock_destroy",
    "pthread_rwlock_rdlock", "pthread_rwlock_wrlock",
    "pthread_rwlock_tryrdlock", "pthread_rwlock_trywrlock", "pthread_rwlock_unlock",
    "pthread_key_create", "pthread_key_delete", "pthread_setspecific", "pthread_getspecific",
    "__pthread_cleanup_push", "__pthread_cleanup_pop",
    "pthread_once", "pthread_gettid_np",
    // missing misc forwards
    "waitpid", "chmod", "fchmod", "fchmodat", "umask", "select",
    "socketpair", "sendmsg", "recvmsg",
    "inet_pton", "inet_ntop", "inet_addr", "inet_ntoa",
    "gethostbyaddr", "gethostbyname", "gethostbyname2", "gethostent",
    "gai_strerror", "if_nameindex", "if_freenameindex",
    "fdopendir", "dirfd",
    "prctl", "lockf", "swab", "pathconf", "getauxval",
    "tcgetattr", "tcsetattr", "getpwuid_r", "__register_atfork",
    "bsd_signal", "kill", "killpg",
    "getifaddrs", "freeifaddrs",
    "mremap",
    // new symbols batch
    "__strchr_chk", "__strrchr_chk", "__strncpy_chk2", "__strlcpy_chk",
    "__read_chk", "__write_chk", "__open_2", "openat",
    "__recvfrom_chk", "__sendto_chk",
    "inet_network", "inet_lnaof", "inet_makeaddr", "inet_netof", "__cmsg_nxthdr",
    "__vsprintf_chk", "__snprintf_chk", "__vsnprintf_chk", "__fgets_chk", "asprintf",
    "__ctype_get_mb_cur_max",
    "_ctype_",
    "_tolower_tab_",
    "_toupper_tab_",
    "mallinfo", "__FD_CLR_chk", "__FD_ISSET_chk", "__FD_SET_chk",
    "drand48", "erand48", "lrand48", "nrand48", "mrand48", "jrand48",
    "srand48", "seed48", "lcong48", "initstate", "setstate",
    "__divdi3", "__udivdi3", "__umoddi3",
    "wcstol", "wcstoul", "wcstoll", "wcstoull", "wcstof", "wcstod", "wcstold",
    "wmemchr", "wmemcmp", "wmemcpy", "wmemset", "wmemmove",
    "wctob", "btowc", "wctype", "fputwc",
    "strftime_l", "strptime_l", "newlocale", "uselocale",
    "__system_property_foreach", "__system_property_read",
    // batch 3: wctype + wchar + locale-aware variants + missing registrations
    "iswspace", "iswctype", "towlower", "towupper",
    "iswlower", "iswprint", "iswblank", "iswcntrl",
    "iswupper", "iswalpha", "iswdigit", "iswpunct", "iswxdigit",
    "towlower_l", "towupper_l",
    "iswlower_l", "iswprint_l", "iswblank_l", "iswcntrl_l",
    "iswupper_l", "iswalpha_l", "iswdigit_l", "iswpunct_l", "iswxdigit_l", "iswspace_l",
    "wcrtomb", "mbrtowc", "wcscoll", "wcsxfrm",
    "mbsnrtowcs", "wcsnrtombs", "wcscoll_l", "wcsxfrm_l", "mbrlen", "wcsftime",
    "strtoul_l", "strtoll_l", "strtoull_l", "strtof_l", "strtold_l",
    "strcoll_l", "strxfrm_l",
    "islower_l", "isupper_l", "isxdigit_l", "isdigit_l", "tolower_l", "toupper_l",
    "freelocale",
    "sscanf", "vprintf", "vasprintf", "vsscanf",
    "sigsetjmp", "siglongjmp",
    // FILE* symbols — bionic::FILE wrapping
    "__sF", "__isthreaded", "stdin", "stdout", "stderr",
    "clearerr", "fclose", "fdopen", "feof", "ferror",
    "fflush", "fgetc", "fgets", "fileno", "flockfile",
    "fopen", "fprintf", "fputc", "fputs", "fread",
    "freopen", "freopen64", "fscanf", "fseek", "fseeko",
    "ftell", "ftello", "ftrylockfile", "funlockfile",
    "fwrite", "getc", "getc_unlocked", "getdelim", "getline",
    "getw", "getwc", "pclose", "popen", "putc",
    "putc_unlocked", "putw", "putwc", "rewind",
    "setbuf", "setbuffer", "setlinebuf", "setvbuf",
    "tmpfile", "ungetc", "ungetwc", "vfprintf", "vfscanf",
];

unsafe fn get_symbol_ptr(name: &str) -> *mut c_void {
    match name {
        "__errno" => errno::__errno as *mut c_void,
        "__set_errno" => errno::__set_errno as *mut c_void,
        "__assert" => assert::__assert as *mut c_void,
        "__assert2" => assert::__assert2 as *mut c_void,
        "__stack_chk_fail" => assert::__stack_chk_fail as *mut c_void,
        "__stack_chk_guard" => &assert::__stack_chk_guard as *const _ as *mut c_void,
        "android_set_abort_message" => assert::android_set_abort_message as *mut c_void,
        "__cxa_atexit" => misc::__cxa_atexit as *mut c_void,
        "__cxa_finalize" => misc::__cxa_finalize as *mut c_void,
        "abort" => assert::abort as *mut c_void,
        "atexit" => stdlib::atexit as *mut c_void,
        "exit" => stdlib::exit as *mut c_void,
        "_Exit" => stdlib::_Exit as *mut c_void,
        "_exit" => stdlib::_exit as *mut c_void,
        "system" => stdlib::system as *mut c_void,
        "getenv" => stdlib::getenv as *mut c_void,
        "putenv" => stdlib::putenv as *mut c_void,
        "setenv" => stdlib::setenv as *mut c_void,
        "unsetenv" => stdlib::unsetenv as *mut c_void,
        "realpath" => stdlib::realpath as *mut c_void,
        "atoi" => stdlib::atoi as *mut c_void,
        "atol" => stdlib::atol as *mut c_void,
        "atoll" => stdlib::atoll as *mut c_void,
        "atof" => stdlib::atof as *mut c_void,
        "strtol" => stdlib::strtol as *mut c_void,
        "strtoul" => stdlib::strtoul as *mut c_void,
        "strtoll" => stdlib::strtoll as *mut c_void,
        "strtoull" => stdlib::strtoull as *mut c_void,
        "strtof" => stdlib::strtof as *mut c_void,
        "strtod" => stdlib::strtod as *mut c_void,
        "strtold" => stdlib::strtold as *mut c_void,
        "strtoq" => stdlib::strtoq as *mut c_void,
        "strtouq" => stdlib::strtouq as *mut c_void,
        "strtoimax" => stdlib::strtoimax as *mut c_void,
        "strtoumax" => stdlib::strtoumax as *mut c_void,
        "abs" => stdlib::abs as *mut c_void,
        "ldexp" => stdlib::ldexp as *mut c_void,
        "bsearch" => stdlib::bsearch as *mut c_void,
        "qsort" => stdlib::qsort as *mut c_void,
        "malloc" => stdlib::malloc as *mut c_void,
        "free" => stdlib::free as *mut c_void,
        "calloc" => stdlib::calloc as *mut c_void,
        "realloc" => stdlib::realloc as *mut c_void,
        "valloc" => stdlib::valloc as *mut c_void,
        "memalign" => stdlib::memalign as *mut c_void,
        "posix_memalign" => stdlib::posix_memalign as *mut c_void,
        "malloc_usable_size" => stdlib::malloc_usable_size as *mut c_void,
        "memcpy" => memory::memcpy as *mut c_void,
        "__memcpy_chk" => memory::__memcpy_chk as *mut c_void,
        "memmove" => memory::memmove as *mut c_void,
        "__memmove_chk" => memory::__memmove_chk as *mut c_void,
        "memset" => memory::memset as *mut c_void,
        "__memset_chk" => memory::__memset_chk as *mut c_void,
        "memcmp" => memory::memcmp as *mut c_void,
        "memchr" => memory::memchr as *mut c_void,
        "memmem" => memory::memmem as *mut c_void,
        "bcmp" => memory::bcmp as *mut c_void,
        "bcopy" => memory::bcopy as *mut c_void,
        "bzero" => memory::bzero as *mut c_void,
        "ffs" => memory::ffs as *mut c_void,
        "index" => memory::index as *mut c_void,
        "rindex" => memory::rindex as *mut c_void,
        "strlen" => string::strlen as *mut c_void,
        "__strlen_chk" => string::__strlen_chk as *mut c_void,
        "strcmp" => string::strcmp as *mut c_void,
        "strncmp" => string::strncmp as *mut c_void,
        "strcpy" => string::strcpy as *mut c_void,
        "__strcpy_chk" => string::__strcpy_chk as *mut c_void,
        "strncpy" => string::strncpy as *mut c_void,
        "__strncpy_chk" => string::__strncpy_chk as *mut c_void,
        "strcat" => string::strcat as *mut c_void,
        "__strcat_chk" => string::__strcat_chk as *mut c_void,
        "strncat" => string::strncat as *mut c_void,
        "__strncat_chk" => string::__strncat_chk as *mut c_void,
        "strdup" => string::strdup as *mut c_void,
        "strndup" => string::strndup as *mut c_void,
        "strchr" => string::strchr as *mut c_void,
        "strrchr" => string::strrchr as *mut c_void,
        "strstr" => string::strstr as *mut c_void,
        "strtok" => string::strtok as *mut c_void,
        "strtok_r" => string::strtok_r as *mut c_void,
        "strerror" => string::strerror as *mut c_void,
        "strerror_r" => string::strerror_r as *mut c_void,
        "strnlen" => string::strnlen as *mut c_void,
        "strlcpy" => string::strlcpy as *mut c_void,
        "strcasecmp" => string::strcasecmp as *mut c_void,
        "strncasecmp" => string::strncasecmp as *mut c_void,
        "strcoll" => string::strcoll as *mut c_void,
        "strxfrm" => string::strxfrm as *mut c_void,
        "strsep" => string::strsep as *mut c_void,
        "strcspn" => string::strcspn as *mut c_void,
        "strpbrk" => string::strpbrk as *mut c_void,
        "strspn" => string::strspn as *mut c_void,
        "strsignal" => string::strsignal as *mut c_void,
        "memccpy" => string::memccpy as *mut c_void,
        "basename" => string::basename as *mut c_void,
        "isalnum" => ctype::isalnum as *mut c_void,
        "isalpha" => ctype::isalpha as *mut c_void,
        "isblank" => ctype::isblank as *mut c_void,
        "iscntrl" => ctype::iscntrl as *mut c_void,
        "isdigit" => ctype::isdigit as *mut c_void,
        "isgraph" => ctype::isgraph as *mut c_void,
        "islower" => ctype::islower as *mut c_void,
        "isprint" => ctype::isprint as *mut c_void,
        "ispunct" => ctype::ispunct as *mut c_void,
        "isspace" => ctype::isspace as *mut c_void,
        "isupper" => ctype::isupper as *mut c_void,
        "isxdigit" => ctype::isxdigit as *mut c_void,
        "isascii" => ctype::isascii as *mut c_void,
        "tolower" => ctype::tolower as *mut c_void,
        "toupper" => ctype::toupper as *mut c_void,
        "printf" => get_shim_printf(),
        "sprintf" => get_shim_sprintf(),
        "snprintf" => get_shim_snprintf(),
        "scanf" => get_shim_scanf(),
        "vsprintf" => stdio::vsprintf as *mut c_void,
        "vsnprintf" => stdio::vsnprintf as *mut c_void,
        "vscanf" => stdio::vscanf as *mut c_void,
        "swprintf" => get_shim_swprintf(),
        "puts" => stdio::puts as *mut c_void,
        "getchar" => stdio::getchar as *mut c_void,
        "putchar" => stdio::putchar as *mut c_void,
        "perror" => stdio::perror as *mut c_void,
        "remove" => stdio::remove as *mut c_void,
        "rename" => stdio::rename as *mut c_void,
        "open" => unistd::open as *mut c_void,
        "open64" => unistd::open64 as *mut c_void,
        "close" => unistd::close as *mut c_void,
        "read" => unistd::read as *mut c_void,
        "write" => unistd::write as *mut c_void,
        "pread" => unistd::pread as *mut c_void,
        "pwrite" => unistd::pwrite as *mut c_void,
        "lseek" => unistd::lseek as *mut c_void,
        "lseek64" => unistd::lseek64 as *mut c_void,
        "dup" => unistd::dup as *mut c_void,
        "dup2" => unistd::dup2 as *mut c_void,
        "pipe" => unistd::pipe as *mut c_void,
        "access" => unistd::access as *mut c_void,
        "unlink" => unistd::unlink as *mut c_void,
        "unlinkat" => unistd::unlinkat as *mut c_void,
        "rmdir" => unistd::rmdir as *mut c_void,
        "mkdir" => unistd::mkdir as *mut c_void,
        "link" => unistd::link as *mut c_void,
        "symlink" => unistd::symlink as *mut c_void,
        "readlink" => unistd::readlink as *mut c_void,
        "chdir" => unistd::chdir as *mut c_void,
        "fchdir" => unistd::fchdir as *mut c_void,
        "getcwd" => unistd::getcwd as *mut c_void,
        "chown" => unistd::chown as *mut c_void,
        "fchown" => unistd::fchown as *mut c_void,
        "lchown" => unistd::lchown as *mut c_void,
        "getuid" => unistd::getuid as *mut c_void,
        "getgid" => unistd::getgid as *mut c_void,
        "geteuid" => unistd::geteuid as *mut c_void,
        "getegid" => unistd::getegid as *mut c_void,
        "getpid" => unistd::getpid as *mut c_void,
        "getppid" => unistd::getppid as *mut c_void,
        "getpgrp" => unistd::getpgrp as *mut c_void,
        "fork" => unistd::fork as *mut c_void,
        "vfork" => unistd::vfork as *mut c_void,
        "execv" => unistd::execv as *mut c_void,
        "execvp" => unistd::execvp as *mut c_void,
        "execl" => unistd::execl as *mut c_void,
        "execle" => unistd::execle as *mut c_void,
        "execlp" => unistd::execlp as *mut c_void,
        "isatty" => unistd::isatty as *mut c_void,
        "alarm" => unistd::alarm as *mut c_void,
        "sleep" => unistd::sleep as *mut c_void,
        "usleep" => unistd::usleep as *mut c_void,
        "pause" => unistd::pause as *mut c_void,
        "fsync" => unistd::fsync as *mut c_void,
        "fdatasync" => unistd::fdatasync as *mut c_void,
        "sync" => unistd::sync as *mut c_void,
        "gethostname" => unistd::gethostname as *mut c_void,
        "getpagesize" => unistd::getpagesize as *mut c_void,
        "truncate" => unistd::truncate as *mut c_void,
        "ftruncate" => unistd::ftruncate as *mut c_void,
        "nice" => unistd::nice as *mut c_void,
        "getdtablesize" => unistd::getdtablesize as *mut c_void,
        "writev" => unistd::writev as *mut c_void,
        "mmap" => mmap::mmap as *mut c_void,
        "munmap" => mmap::munmap as *mut c_void,
        "mprotect" => mmap::mprotect as *mut c_void,
        "madvise" => mmap::madvise as *mut c_void,
        "msync" => mmap::msync as *mut c_void,
        "mlock" => mmap::mlock as *mut c_void,
        "munlock" => mmap::munlock as *mut c_void,
        "signal" => signal_::signal as *mut c_void,
        "raise" => signal_::raise as *mut c_void,
        "sigaction" => signal_::sigaction as *mut c_void,
        "sigprocmask" => signal_::sigprocmask as *mut c_void,
        "sigemptyset" => signal_::sigemptyset as *mut c_void,
        "sigfillset" => signal_::sigfillset as *mut c_void,
        "sigaddset" => signal_::sigaddset as *mut c_void,
        "sigdelset" => signal_::sigdelset as *mut c_void,
        "time" => time::time as *mut c_void,
        "clock" => time::clock as *mut c_void,
        "difftime" => time::difftime as *mut c_void,
        "mktime" => time::mktime as *mut c_void,
        "gmtime" => time::gmtime as *mut c_void,
        "gmtime_r" => time::gmtime_r as *mut c_void,
        "localtime" => time::localtime as *mut c_void,
        "localtime_r" => time::localtime_r as *mut c_void,
        "strftime" => time::strftime as *mut c_void,
        "strptime" => time::strptime as *mut c_void,
        "asctime" => time::asctime as *mut c_void,
        "ctime" => time::ctime as *mut c_void,
        "asctime_r" => time::asctime_r as *mut c_void,
        "ctime_r" => time::ctime_r as *mut c_void,
        "tzset" => time::tzset as *mut c_void,
        "tzname" => &raw const time::tzname as *const _ as *mut c_void,
        "daylight" => &raw const time::daylight as *const _ as *mut c_void,
        "timezone" => &raw const time::timezone as *const _ as *mut c_void,
        "nanosleep" => time::nanosleep as *mut c_void,
        "gettimeofday" => time::gettimeofday as *mut c_void,
        "clock_gettime" => time::clock_gettime as *mut c_void,
        "clock_getres" => time::clock_getres as *mut c_void,
        "setlocale" => locale::setlocale as *mut c_void,
        "localeconv" => locale::localeconv as *mut c_void,
        "socket" => socket::socket as *mut c_void,
        "bind" => socket::bind as *mut c_void,
        "connect" => socket::connect as *mut c_void,
        "listen" => socket::listen as *mut c_void,
        "accept" => socket::accept as *mut c_void,
        "accept4" => socket::accept4 as *mut c_void,
        "send" => socket::send as *mut c_void,
        "recv" => socket::recv as *mut c_void,
        "sendto" => socket::sendto as *mut c_void,
        "recvfrom" => socket::recvfrom as *mut c_void,
        "getsockname" => socket::getsockname as *mut c_void,
        "getpeername" => socket::getpeername as *mut c_void,
        "getsockopt" => socket::getsockopt as *mut c_void,
        "setsockopt" => socket::setsockopt as *mut c_void,
        "shutdown" => socket::shutdown as *mut c_void,
        "getaddrinfo" => socket::getaddrinfo as *mut c_void,
        "freeaddrinfo" => socket::freeaddrinfo as *mut c_void,
        "getnameinfo" => socket::getnameinfo as *mut c_void,
        "if_nametoindex" => socket::if_nametoindex as *mut c_void,
        "if_indextoname" => socket::if_indextoname as *mut c_void,
        "sendfile" => socket::sendfile as *mut c_void,
        "stat" => stat::stat as *mut c_void,
        "fstat" => stat::fstat as *mut c_void,
        "lstat" => stat::lstat as *mut c_void,
        "stat64" => stat::stat64 as *mut c_void,
        "fstat64" => stat::fstat64 as *mut c_void,
        "lstat64" => stat::lstat64 as *mut c_void,
        "mkfifo" => stat::mkfifo as *mut c_void,
        "mknod" => stat::mknod as *mut c_void,
        "utime" => stat::utime as *mut c_void,
        "utimes" => stat::utimes as *mut c_void,
        "utimensat" => stat::utimensat as *mut c_void,
        "futimens" => stat::futimens as *mut c_void,
        "statfs" => stat::statfs as *mut c_void,
        "fstatfs" => stat::fstatfs as *mut c_void,
        "statvfs" => stat::statvfs as *mut c_void,
        "fstatvfs" => stat::fstatvfs as *mut c_void,
        "opendir" => dir::opendir as *mut c_void,
        "closedir" => dir::closedir as *mut c_void,
        "readdir" => dir::readdir as *mut c_void,
        "readdir_r" => dir::readdir_r as *mut c_void,
        "rewinddir" => dir::rewinddir as *mut c_void,
        "seekdir" => dir::seekdir as *mut c_void,
        "telldir" => dir::telldir as *mut c_void,
        "scandir" => dir::scandir as *mut c_void,
        "alphasort" => dir::alphasort as *mut c_void,
        "versionsort" => dir::versionsort as *mut c_void,
        "mkdtemp" => dir::mkdtemp as *mut c_void,
        "ioctl" => misc::ioctl as *mut c_void,
        "fcntl" => misc::fcntl as *mut c_void,
        "poll" => misc::poll as *mut c_void,
        "getrlimit" => misc::getrlimit as *mut c_void,
        "setrlimit" => misc::setrlimit as *mut c_void,
        "getrusage" => misc::getrusage as *mut c_void,
        "getpriority" => misc::getpriority as *mut c_void,
        "setpriority" => misc::setpriority as *mut c_void,
        "sched_yield" => misc::sched_yield as *mut c_void,
        "sched_get_priority_min" => misc::sched_get_priority_min as *mut c_void,
        "sched_get_priority_max" => misc::sched_get_priority_max as *mut c_void,
        "sched_setaffinity" => misc::sched_setaffinity as *mut c_void,
        "sched_getaffinity" => misc::sched_getaffinity as *mut c_void,
        "openlog" => misc::openlog as *mut c_void,
        "closelog" => misc::closelog as *mut c_void,
        "syslog" => misc::syslog as *mut c_void,
        "uname" => misc::uname as *mut c_void,
        "random" => misc::random as *mut c_void,
        "srandom" => misc::srandom as *mut c_void,
        "rand" => misc::rand as *mut c_void,
        "srand" => misc::srand as *mut c_void,
        "rand_r" => misc::rand_r as *mut c_void,
        "dlopen" => misc::dlopen as *mut c_void,
        "dlsym" => misc::dlsym as *mut c_void,
        "dlclose" => misc::dlclose as *mut c_void,
        "dlerror" => misc::dlerror as *mut c_void,
        "dladdr" => misc::dladdr as *mut c_void,
        "fnmatch" => misc::fnmatch as *mut c_void,
        "wcslen" => misc::wcslen as *mut c_void,
        "wcscpy" => misc::wcscpy as *mut c_void,
        "wcsncpy" => misc::wcsncpy as *mut c_void,
        "wcscmp" => misc::wcscmp as *mut c_void,
        "wcscat" => misc::wcscat as *mut c_void,
        "isnan" => misc::isnan as *mut c_void,
        "finite" => misc::finite as *mut c_void,
        "_Znwj" => stdlib::_Znwj as *mut c_void,
        "_Znaj" => stdlib::_Znaj as *mut c_void,
        "_Znwm" => stdlib::_Znwm as *mut c_void,
        "_Znam" => stdlib::_Znam as *mut c_void,
        "_ZdlPv" => stdlib::_ZdlPv as *mut c_void,
        "_ZdaPv" => stdlib::_ZdaPv as *mut c_void,
        "_ZnwjSt11align_val_t" => stdlib::_ZnwjSt11align_val_t as *mut c_void,
        "_ZnwmSt11align_val_t" => stdlib::_ZnwmSt11align_val_t as *mut c_void,
        "gettid" => misc::gettid as *mut c_void,
        "getrandom" => misc::getrandom as *mut c_void,
        "syscall" => get_shim_syscall(),
        "arc4random_buf" => misc::arc4random_buf as *mut c_void,
        "arc4random" => misc::arc4random as *mut c_void,
        "getentropy" => misc::getentropy as *mut c_void,
        "mblen" => misc::mblen as *mut c_void,
        "mbtowc" => misc::mbtowc as *mut c_void,
        "wctomb" => misc::wctomb as *mut c_void,
        "mbstowcs" => misc::mbstowcs as *mut c_void,
        "wcstombs" => misc::wcstombs as *mut c_void,
        "wcsrtombs" => misc::wcsrtombs as *mut c_void,
        "mbsrtowcs" => misc::mbsrtowcs as *mut c_void,
        "epoll_create" => misc::epoll_create as *mut c_void,
        "epoll_create1" => misc::epoll_create1 as *mut c_void,
        "epoll_ctl" => misc::epoll_ctl as *mut c_void,
        "epoll_wait" => misc::epoll_wait as *mut c_void,
        "eventfd" => misc::eventfd as *mut c_void,
        "sem_init" => misc::sem_init as *mut c_void,
        "sem_destroy" => misc::sem_destroy as *mut c_void,
        "sem_wait" => misc::sem_wait as *mut c_void,
        "sem_timedwait" => misc::sem_timedwait as *mut c_void,
        "sem_post" => misc::sem_post as *mut c_void,
        "setjmp" => misc::setjmp as *mut c_void,
        "longjmp" => misc::longjmp as *mut c_void,
        "sysconf" => misc::sysconf as *mut c_void,
        "__system_property_find" => misc::__system_property_find as *mut c_void,
        "__system_property_get" => misc::__system_property_get as *mut c_void,
        "__system_property_read_callback" => misc::__system_property_read_callback as *mut c_void,
        // data
        // pthreads
        "pthread_create" => pthreads::pthread_create as *mut c_void,
        "pthread_join" => pthreads::pthread_join as *mut c_void,
        "pthread_detach" => pthreads::pthread_detach as *mut c_void,
        "pthread_kill" => pthreads::pthread_kill as *mut c_void,
        "pthread_self" => pthreads::pthread_self as *mut c_void,
        "pthread_equal" => pthreads::pthread_equal as *mut c_void,
        "pthread_atfork" => pthreads::pthread_atfork as *mut c_void,
        "pthread_setschedparam" => pthreads::pthread_setschedparam as *mut c_void,
        "pthread_getschedparam" => pthreads::pthread_getschedparam as *mut c_void,
        "pthread_getattr_np" => pthreads::pthread_getattr_np as *mut c_void,
        "pthread_attr_init" => pthreads::pthread_attr_init as *mut c_void,
        "pthread_attr_destroy" => pthreads::pthread_attr_destroy as *mut c_void,
        "pthread_attr_setdetachstate" => pthreads::pthread_attr_setdetachstate as *mut c_void,
        "pthread_attr_getdetachstate" => pthreads::pthread_attr_getdetachstate as *mut c_void,
        "pthread_attr_setschedparam" => pthreads::pthread_attr_setschedparam as *mut c_void,
        "pthread_attr_getschedparam" => pthreads::pthread_attr_getschedparam as *mut c_void,
        "pthread_attr_setstacksize" => pthreads::pthread_attr_setstacksize as *mut c_void,
        "pthread_attr_getstack" => pthreads::pthread_attr_getstack as *mut c_void,
        "pthread_attr_getstacksize" => pthreads::pthread_attr_getstacksize as *mut c_void,
        "pthread_setname_np" => pthreads::pthread_setname_np as *mut c_void,
        "pthread_mutex_init" => pthreads::pthread_mutex_init as *mut c_void,
        "pthread_mutex_destroy" => pthreads::pthread_mutex_destroy as *mut c_void,
        "pthread_mutex_lock" => pthreads::pthread_mutex_lock as *mut c_void,
        "pthread_mutex_unlock" => pthreads::pthread_mutex_unlock as *mut c_void,
        "pthread_mutex_trylock" => pthreads::pthread_mutex_trylock as *mut c_void,
        "pthread_mutexattr_init" => pthreads::pthread_mutexattr_init as *mut c_void,
        "pthread_mutexattr_destroy" => pthreads::pthread_mutexattr_destroy as *mut c_void,
        "pthread_mutexattr_settype" => pthreads::pthread_mutexattr_settype as *mut c_void,
        "pthread_mutexattr_gettype" => pthreads::pthread_mutexattr_gettype as *mut c_void,
        "pthread_cond_init" => pthreads::pthread_cond_init as *mut c_void,
        "pthread_cond_destroy" => pthreads::pthread_cond_destroy as *mut c_void,
        "pthread_cond_wait" => pthreads::pthread_cond_wait as *mut c_void,
        "pthread_cond_broadcast" => pthreads::pthread_cond_broadcast as *mut c_void,
        "pthread_cond_signal" => pthreads::pthread_cond_signal as *mut c_void,
        "pthread_cond_timedwait" => pthreads::pthread_cond_timedwait as *mut c_void,
        "pthread_cond_timedwait_monotonic_np" => pthreads::pthread_cond_timedwait as *mut c_void,
        "pthread_condattr_init" => pthreads::pthread_condattr_init as *mut c_void,
        "pthread_condattr_destroy" => pthreads::pthread_condattr_destroy as *mut c_void,
        "pthread_condattr_setclock" => pthreads::pthread_condattr_setclock as *mut c_void,
        "pthread_condattr_getclock" => pthreads::pthread_condattr_getclock as *mut c_void,
        "pthread_rwlock_init" => pthreads::pthread_rwlock_init as *mut c_void,
        "pthread_rwlock_destroy" => pthreads::pthread_rwlock_destroy as *mut c_void,
        "pthread_rwlock_rdlock" => pthreads::pthread_rwlock_rdlock as *mut c_void,
        "pthread_rwlock_wrlock" => pthreads::pthread_rwlock_wrlock as *mut c_void,
        "pthread_rwlock_tryrdlock" => pthreads::pthread_rwlock_tryrdlock as *mut c_void,
        "pthread_rwlock_trywrlock" => pthreads::pthread_rwlock_trywrlock as *mut c_void,
        "pthread_rwlock_unlock" => pthreads::pthread_rwlock_unlock as *mut c_void,
        "pthread_key_create" => pthreads::pthread_key_create as *mut c_void,
        "pthread_key_delete" => pthreads::pthread_key_delete as *mut c_void,
        "pthread_setspecific" => pthreads::pthread_setspecific as *mut c_void,
        "pthread_getspecific" => pthreads::pthread_getspecific as *mut c_void,
        "__pthread_cleanup_push" => pthreads::__pthread_cleanup_push as *mut c_void,
        "__pthread_cleanup_pop" => pthreads::__pthread_cleanup_pop as *mut c_void,
        "pthread_once" => pthreads::pthread_once as *mut c_void,
        "pthread_gettid_np" => pthreads::pthread_gettid_np as *mut c_void,
        // misc forwards
        "waitpid" => misc::waitpid as *mut c_void,
        "chmod" => misc::chmod as *mut c_void,
        "fchmod" => misc::fchmod as *mut c_void,
        "fchmodat" => misc::fchmodat as *mut c_void,
        "umask" => misc::umask as *mut c_void,
        "select" => misc::select as *mut c_void,
        "socketpair" => socket::socketpair as *mut c_void,
        "sendmsg" => socket::sendmsg as *mut c_void,
        "recvmsg" => socket::recvmsg as *mut c_void,
        "inet_pton" => socket::inet_pton as *mut c_void,
        "inet_ntop" => socket::inet_ntop as *mut c_void,
        "inet_addr" => socket::inet_addr as *mut c_void,
        "inet_ntoa" => socket::inet_ntoa as *mut c_void,
        "gethostbyaddr" => socket::gethostbyaddr as *mut c_void,
        "gethostbyname" => socket::gethostbyname as *mut c_void,
        "gethostbyname2" => socket::gethostbyname2 as *mut c_void,
        "gethostent" => socket::gethostent as *mut c_void,
        "gai_strerror" => socket::gai_strerror as *mut c_void,
        "if_nameindex" => socket::if_nameindex as *mut c_void,
        "if_freenameindex" => socket::if_freenameindex as *mut c_void,
        "fdopendir" => dir::fdopendir as *mut c_void,
        "dirfd" => dir::dirfd as *mut c_void,
        "prctl" => misc::prctl as *mut c_void,
        "lockf" => misc::lockf as *mut c_void,
        "swab" => misc::swab as *mut c_void,
        "pathconf" => misc::pathconf as *mut c_void,
        "getauxval" => misc::getauxval as *mut c_void,
        "tcgetattr" => misc::tcgetattr as *mut c_void,
        "tcsetattr" => misc::tcsetattr as *mut c_void,
        "getpwuid_r" => misc::getpwuid_r as *mut c_void,
        "__register_atfork" => misc::__register_atfork as *mut c_void,
        "bsd_signal" => signal_::bsd_signal as *mut c_void,
        "kill" => signal_::kill as *mut c_void,
        "killpg" => signal_::killpg as *mut c_void,
        "getifaddrs" => misc::getifaddrs as *mut c_void,
        "freeifaddrs" => misc::freeifaddrs as *mut c_void,
        "mremap" => mmap::mremap as *mut c_void,
        "__strchr_chk" => string::__strchr_chk as *mut c_void,
        "__strrchr_chk" => string::__strrchr_chk as *mut c_void,
        "__strncpy_chk2" => string::__strncpy_chk2 as *mut c_void,
        "__strlcpy_chk" => string::__strlcpy_chk as *mut c_void,
        "__read_chk" => unistd::__read_chk as *mut c_void,
        "__write_chk" => unistd::__write_chk as *mut c_void,
        "__open_2" => unistd::__open_2 as *mut c_void,
        "openat" => unistd::openat as *mut c_void,
        "__recvfrom_chk" => socket::__recvfrom_chk as *mut c_void,
        "__sendto_chk" => socket::__sendto_chk as *mut c_void,
        "inet_network" => socket::inet_network as *mut c_void,
        "inet_lnaof" => socket::inet_lnaof as *mut c_void,
        "inet_makeaddr" => socket::inet_makeaddr as *mut c_void,
        "inet_netof" => socket::inet_netof as *mut c_void,
        "__cmsg_nxthdr" => socket::__cmsg_nxthdr as *mut c_void,
        "__vsprintf_chk" => stdio::__vsprintf_chk as *mut c_void,
        "__snprintf_chk" => get_shim___snprintf_chk(),
        "__vsnprintf_chk" => stdio::__vsnprintf_chk as *mut c_void,
        "__fgets_chk" => file::__fgets_chk as *mut c_void,
        "asprintf" => get_shim_asprintf(),
        "__ctype_get_mb_cur_max" => ctype::__ctype_get_mb_cur_max as *mut c_void,
        "_ctype_" => &ctype::_CTYPE_PTR.0 as *const *const u8 as *mut c_void,
        "_tolower_tab_" => &ctype::_TOLOWER_PTR.0 as *const *const i16 as *mut c_void,
        "_toupper_tab_" => &ctype::_TOUPPER_PTR.0 as *const *const i16 as *mut c_void,
        "mallinfo" => misc::mallinfo as *mut c_void,
        "__FD_CLR_chk" => misc::__FD_CLR_chk as *mut c_void,
        "__FD_ISSET_chk" => misc::__FD_ISSET_chk as *mut c_void,
        "__FD_SET_chk" => misc::__FD_SET_chk as *mut c_void,
        "drand48" => misc::drand48 as *mut c_void,
        "erand48" => misc::erand48 as *mut c_void,
        "lrand48" => misc::lrand48 as *mut c_void,
        "nrand48" => misc::nrand48 as *mut c_void,
        "mrand48" => misc::mrand48 as *mut c_void,
        "jrand48" => misc::jrand48 as *mut c_void,
        "srand48" => misc::srand48 as *mut c_void,
        "seed48" => misc::seed48 as *mut c_void,
        "lcong48" => misc::lcong48 as *mut c_void,
        "initstate" => misc::initstate as *mut c_void,
        "setstate" => misc::setstate as *mut c_void,
        "__divdi3" => misc::__divdi3 as *mut c_void,
        "__udivdi3" => misc::__udivdi3 as *mut c_void,
        "__umoddi3" => misc::__umoddi3 as *mut c_void,
        "wcstol" => misc::wcstol as *mut c_void,
        "wcstoul" => misc::wcstoul as *mut c_void,
        "wcstoll" => misc::wcstoll as *mut c_void,
        "wcstoull" => misc::wcstoull as *mut c_void,
        "wcstof" => misc::wcstof as *mut c_void,
        "wcstod" => misc::wcstod as *mut c_void,
        "wcstold" => misc::wcstold as *mut c_void,
        "wmemchr" => misc::wmemchr as *mut c_void,
        "wmemcmp" => misc::wmemcmp as *mut c_void,
        "wmemcpy" => misc::wmemcpy as *mut c_void,
        "wmemset" => misc::wmemset as *mut c_void,
        "wmemmove" => misc::wmemmove as *mut c_void,
        "wctob" => misc::wctob as *mut c_void,
        "btowc" => misc::btowc as *mut c_void,
        "wctype" => misc::wctype as *mut c_void,
        "fputwc" => file::fputwc as *mut c_void,
        "strftime_l" => time::strftime_l as *mut c_void,
        "strptime_l" => time::strptime_l as *mut c_void,
        "newlocale" => locale::newlocale as *mut c_void,
        "uselocale" => locale::uselocale as *mut c_void,
        "__system_property_foreach" => misc::__system_property_foreach as *mut c_void,
        "__system_property_read" => misc::__system_property_read as *mut c_void,
        // batch 3
        "iswspace" => misc::iswspace as *mut c_void,
        "iswctype" => misc::iswctype as *mut c_void,
        "towlower" => misc::towlower as *mut c_void,
        "towupper" => misc::towupper as *mut c_void,
        "iswlower" => misc::iswlower as *mut c_void,
        "iswprint" => misc::iswprint as *mut c_void,
        "iswblank" => misc::iswblank as *mut c_void,
        "iswcntrl" => misc::iswcntrl as *mut c_void,
        "iswupper" => misc::iswupper as *mut c_void,
        "iswalpha" => misc::iswalpha as *mut c_void,
        "iswdigit" => misc::iswdigit as *mut c_void,
        "iswpunct" => misc::iswpunct as *mut c_void,
        "iswxdigit" => misc::iswxdigit as *mut c_void,
        "towlower_l" => misc::towlower_l as *mut c_void,
        "towupper_l" => misc::towupper_l as *mut c_void,
        "iswlower_l" => misc::iswlower_l as *mut c_void,
        "iswprint_l" => misc::iswprint_l as *mut c_void,
        "iswblank_l" => misc::iswblank_l as *mut c_void,
        "iswcntrl_l" => misc::iswcntrl_l as *mut c_void,
        "iswupper_l" => misc::iswupper_l as *mut c_void,
        "iswalpha_l" => misc::iswalpha_l as *mut c_void,
        "iswdigit_l" => misc::iswdigit_l as *mut c_void,
        "iswpunct_l" => misc::iswpunct_l as *mut c_void,
        "iswxdigit_l" => misc::iswxdigit_l as *mut c_void,
        "iswspace_l" => misc::iswspace_l as *mut c_void,
        "wcrtomb" => misc::wcrtomb as *mut c_void,
        "mbrtowc" => misc::mbrtowc as *mut c_void,
        "wcscoll" => misc::wcscoll as *mut c_void,
        "wcsxfrm" => misc::wcsxfrm as *mut c_void,
        "mbsnrtowcs" => misc::mbsnrtowcs as *mut c_void,
        "wcsnrtombs" => misc::wcsnrtombs as *mut c_void,
        "wcscoll_l" => misc::wcscoll_l as *mut c_void,
        "wcsxfrm_l" => misc::wcsxfrm_l as *mut c_void,
        "mbrlen" => misc::mbrlen as *mut c_void,
        "wcsftime" => misc::wcsftime as *mut c_void,
        "strtoul_l" => stdlib::strtoul_l as *mut c_void,
        "strtoll_l" => stdlib::strtoll_l as *mut c_void,
        "strtoull_l" => stdlib::strtoull_l as *mut c_void,
        "strtof_l" => stdlib::strtof_l as *mut c_void,
        "strtold_l" => stdlib::strtold_l as *mut c_void,
        "strcoll_l" => string::strcoll_l as *mut c_void,
        "strxfrm_l" => string::strxfrm_l as *mut c_void,
        "islower_l" => ctype::islower_l as *mut c_void,
        "isupper_l" => ctype::isupper_l as *mut c_void,
        "isxdigit_l" => ctype::isxdigit_l as *mut c_void,
        "isdigit_l" => ctype::isdigit_l as *mut c_void,
        "tolower_l" => ctype::tolower_l as *mut c_void,
        "toupper_l" => ctype::toupper_l as *mut c_void,
        "freelocale" => locale::freelocale as *mut c_void,
        "sscanf" => get_shim_sscanf(),
        "vprintf" => stdio::vprintf as *mut c_void,
        "vasprintf" => stdio::vasprintf as *mut c_void,
        "vsscanf" => stdio::vsscanf as *mut c_void,
        "sigsetjmp" => misc::sigsetjmp as *mut c_void,
        "siglongjmp" => misc::siglongjmp as *mut c_void,
        // FILE* data symbols
        "__sF" => file::get_sf_addr(),
        "__isthreaded" => &raw const file::__isthreaded as *const c_int as *mut c_void,
        "stdin" => file::get_stdin_ptr_addr(),
        "stdout" => file::get_stdout_ptr_addr(),
        "stderr" => file::get_stderr_ptr_addr(),
        // FILE* function symbols
        "clearerr" => file::clearerr as *mut c_void,
        "fclose" => file::fclose as *mut c_void,
        "fdopen" => file::fdopen as *mut c_void,
        "feof" => file::feof as *mut c_void,
        "ferror" => file::ferror as *mut c_void,
        "fflush" => file::fflush as *mut c_void,
        "fgetc" => file::fgetc as *mut c_void,
        "fgets" => file::fgets as *mut c_void,
        "fileno" => file::fileno as *mut c_void,
        "flockfile" => file::flockfile as *mut c_void,
        "fopen" => file::fopen as *mut c_void,
        "fprintf" => get_shim_fprintf(),
        "fputc" => file::fputc as *mut c_void,
        "fputs" => file::fputs as *mut c_void,
        "fread" => file::fread as *mut c_void,
        "freopen" => file::freopen as *mut c_void,
        "freopen64" => file::freopen64 as *mut c_void,
        "fscanf" => get_shim_fscanf(),
        "fseek" => file::fseek as *mut c_void,
        "fseeko" => file::fseeko as *mut c_void,
        "ftell" => file::ftell as *mut c_void,
        "ftello" => file::ftello as *mut c_void,
        "ftrylockfile" => file::ftrylockfile as *mut c_void,
        "funlockfile" => file::funlockfile as *mut c_void,
        "fwrite" => file::fwrite as *mut c_void,
        "getc" => file::getc as *mut c_void,
        "getc_unlocked" => file::getc_unlocked as *mut c_void,
        "getdelim" => file::getdelim as *mut c_void,
        "getline" => file::getline as *mut c_void,
        "getw" => file::getw as *mut c_void,
        "getwc" => file::getwc as *mut c_void,
        "pclose" => file::pclose as *mut c_void,
        "popen" => file::popen as *mut c_void,
        "putc" => file::putc as *mut c_void,
        "putc_unlocked" => file::putc_unlocked as *mut c_void,
        "putw" => file::putw as *mut c_void,
        "putwc" => file::putwc as *mut c_void,
        "rewind" => file::rewind as *mut c_void,
        "setbuf" => file::setbuf as *mut c_void,
        "setbuffer" => file::setbuffer as *mut c_void,
        "setlinebuf" => file::setlinebuf as *mut c_void,
        "setvbuf" => file::setvbuf as *mut c_void,
        "tmpfile" => file::tmpfile as *mut c_void,
        "ungetc" => file::ungetc as *mut c_void,
        "ungetwc" => file::ungetwc as *mut c_void,
        "vfprintf" => file::vfprintf as *mut c_void,
        "vfscanf" => file::vfscanf as *mut c_void,
        _ => std::ptr::null_mut(),
    }
}
